version: "3"

services:
  rest_service_api:
    container_name: rest_service_api
    build:
      dockerfile: Dockerfile.dev
      context: ./rest-service
    ports:
      - "5000:5000"
    volumes:
      - ./rest-service:/home/node/app
      - /home/node/app/node_modules
    environment:
      NODE_ENV: 'development'
      REST_SERVICE_PORT: 5000
    restart: unless-stopped
    networks:
      - pulse_repo

networks:
  pulse_repo:
